# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/college studies/sem 6/HDL/CH11_IMAGE_PROCESSING_VGA/CH11_IMAGE_PROCESSING_VGA/IMAGE_PROCESSING_BASYS3/IMAGE_PROCESSING_BASYS3.srcs/sources_1/ip/image/image.xci
# IP: The module: 'image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/college studies/sem 6/HDL/CH11_IMAGE_PROCESSING_VGA/CH11_IMAGE_PROCESSING_VGA/IMAGE_PROCESSING_BASYS3/IMAGE_PROCESSING_BASYS3.gen/sources_1/ip/image/image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/college studies/sem 6/HDL/CH11_IMAGE_PROCESSING_VGA/CH11_IMAGE_PROCESSING_VGA/IMAGE_PROCESSING_BASYS3/IMAGE_PROCESSING_BASYS3.srcs/sources_1/ip/image/image.xci
# IP: The module: 'image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/college studies/sem 6/HDL/CH11_IMAGE_PROCESSING_VGA/CH11_IMAGE_PROCESSING_VGA/IMAGE_PROCESSING_BASYS3/IMAGE_PROCESSING_BASYS3.gen/sources_1/ip/image/image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
